### ISSUE TITLE
一点卵用也没有

### ISSUE THREAD

**Issue by Yuri2** [xadhrit/xira#8]
一点卵用也没有，垃圾代码。吐吐吐

**Comment by xadhrit** [comment]
💯 i know , can you help me to improve ?

**Comment by xadhrit** [comment]
我知道，您能帮我改善吗？

**Comment by Yuri2** [comment]
现在很多网址都要带cookie，稍微换一个网址就用不了。说白了就是一个简单的网页匹配，然后再加xss代码发送。不灵活，而且能匹配的网址很少。https://weibo.com/像这种啥也没匹配到。

**Comment by Yuri2** [comment]
我找下其他的二开，你这个二开太麻烦了

**Comment by xadhrit** [comment]
cookie支持是由其他开发人员添加的 @naivenom ，但我现在将尝试对其进行更改 .

**Comment by xadhrit** [comment]
感谢您的反馈意见

**Comment by Yuri2** [comment]
如果能对接上burp那就更好了
